/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BankVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "AUDITOR_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "TEN_K"
      | "addAuditor"
      | "approveEscrow"
      | "approveLoan"
      | "approveRedeem"
      | "balances"
      | "blacklisted"
      | "dailyStats"
      | "deposit"
      | "depositApyBps"
      | "depositFromExternal"
      | "ethPerSUSDE18"
      | "forceLockAccount"
      | "freqStats"
      | "frequencyWindow"
      | "getEscrow"
      | "getLoanCase"
      | "getRedeemCase"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "identity"
      | "lockDuration"
      | "lockedUntil"
      | "logContract"
      | "maxTxPerWindow"
      | "nextCaseId"
      | "nextLoanId"
      | "nextRedeemId"
      | "pause"
      | "paused"
      | "redeemToAsset"
      | "rejectEscrow"
      | "rejectLoan"
      | "rejectRedeem"
      | "removeAuditor"
      | "renounceRole"
      | "repayLoan"
      | "requestLoan"
      | "revokeRole"
      | "riskEngine"
      | "setBlacklist"
      | "setDepositApyBps"
      | "setFrequencyParams"
      | "supportsInterface"
      | "token"
      | "transfer"
      | "unlockAccount"
      | "unpause"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "EscrowApproved"
      | "EscrowCreated"
      | "EscrowRejected"
      | "ImmediateTransfer"
      | "LoanApproved"
      | "LoanRejected"
      | "LoanRepaid"
      | "LoanRequested"
      | "RedeemApproved"
      | "RedeemRejected"
      | "RedeemRequested"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AUDITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TEN_K", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addAuditor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveLoan",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveRedeem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositApyBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositFromExternal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ethPerSUSDE18",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forceLockAccount",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "freqStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "frequencyWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanCase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRedeemCase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "identity", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lockDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockedUntil",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTxPerWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextCaseId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextLoanId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextRedeemId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeemToAsset",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectEscrow",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectLoan",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectRedeem",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAuditor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "repayLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "riskEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBlacklist",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositApyBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFrequencyParams",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "AUDITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TEN_K", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addAuditor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveRedeem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dailyStats", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositApyBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFromExternal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethPerSUSDE18",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceLockAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "freqStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "frequencyWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLoanCase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRedeemCase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "identity", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockedUntil",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTxPerWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextCaseId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextLoanId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextRedeemId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redeemToAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rejectLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rejectRedeem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAuditor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "riskEngine", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositApyBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFrequencyParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unlockAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowApprovedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    caseId: bigint,
    from: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    caseId: bigint;
    from: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    caseId: bigint,
    from: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    caseId: bigint;
    from: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRejectedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    caseId: bigint,
    from: string,
    to: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    caseId: bigint;
    from: string;
    to: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ImmediateTransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, amount: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanApprovedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    principal: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    principal: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    principal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRejectedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    principal: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    principal: bigint,
    reason: string
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    principal: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [borrower: AddressLike, amount: BigNumberish];
  export type OutputTuple = [borrower: string, amount: bigint];
  export interface OutputObject {
    borrower: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRequestedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    principal: BigNumberish,
    rateBps: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    principal: bigint,
    rateBps: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    principal: bigint;
    rateBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemApprovedEvent {
  export type InputTuple = [
    redeemId: BigNumberish,
    user: AddressLike,
    susdAmount: BigNumberish,
    ethAmount: BigNumberish
  ];
  export type OutputTuple = [
    redeemId: bigint,
    user: string,
    susdAmount: bigint,
    ethAmount: bigint
  ];
  export interface OutputObject {
    redeemId: bigint;
    user: string;
    susdAmount: bigint;
    ethAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemRejectedEvent {
  export type InputTuple = [
    redeemId: BigNumberish,
    user: AddressLike,
    susdAmount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    redeemId: bigint,
    user: string,
    susdAmount: bigint,
    reason: string
  ];
  export interface OutputObject {
    redeemId: bigint;
    user: string;
    susdAmount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemRequestedEvent {
  export type InputTuple = [
    redeemId: BigNumberish,
    user: AddressLike,
    assetSymbol: string,
    susdAmount: BigNumberish
  ];
  export type OutputTuple = [
    redeemId: bigint,
    user: string,
    assetSymbol: string,
    susdAmount: bigint
  ];
  export interface OutputObject {
    redeemId: bigint;
    user: string;
    assetSymbol: string;
    susdAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BankVault extends BaseContract {
  connect(runner?: ContractRunner | null): BankVault;
  waitForDeployment(): Promise<this>;

  interface: BankVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  AUDITOR_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  TEN_K: TypedContractMethod<[], [bigint], "view">;

  addAuditor: TypedContractMethod<[auditor: AddressLike], [void], "nonpayable">;

  approveEscrow: TypedContractMethod<
    [caseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveLoan: TypedContractMethod<
    [loanId: BigNumberish, ethAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveRedeem: TypedContractMethod<
    [redeemId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  blacklisted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  dailyStats: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { day: bigint; spent: bigint }],
    "view"
  >;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  depositApyBps: TypedContractMethod<[], [bigint], "view">;

  depositFromExternal: TypedContractMethod<
    [susdAmount: BigNumberish],
    [void],
    "payable"
  >;

  ethPerSUSDE18: TypedContractMethod<[], [bigint], "view">;

  forceLockAccount: TypedContractMethod<
    [user: AddressLike, until: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  freqStats: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { windowStart: bigint; count: bigint }],
    "view"
  >;

  frequencyWindow: TypedContractMethod<[], [bigint], "view">;

  getEscrow: TypedContractMethod<
    [caseId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        from_: string;
        to_: string;
        amount_: bigint;
        status_: bigint;
        createdAt_: bigint;
        approvals_: bigint;
      }
    ],
    "view"
  >;

  getLoanCase: TypedContractMethod<
    [loanId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        borrower_: string;
        principal_: bigint;
        rateBps_: bigint;
        status_: bigint;
        createdAt_: bigint;
        approvals_: bigint;
      }
    ],
    "view"
  >;

  getRedeemCase: TypedContractMethod<
    [redeemId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        user_: string;
        assetSymbol_: string;
        susdAmount_: bigint;
        ethAmount_: bigint;
        status_: bigint;
        createdAt_: bigint;
        approvals_: bigint;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  identity: TypedContractMethod<[], [string], "view">;

  lockDuration: TypedContractMethod<[], [bigint], "view">;

  lockedUntil: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  logContract: TypedContractMethod<[], [string], "view">;

  maxTxPerWindow: TypedContractMethod<[], [bigint], "view">;

  nextCaseId: TypedContractMethod<[], [bigint], "view">;

  nextLoanId: TypedContractMethod<[], [bigint], "view">;

  nextRedeemId: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  redeemToAsset: TypedContractMethod<
    [assetSymbol: string, susdAmount: BigNumberish, ethAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  rejectEscrow: TypedContractMethod<
    [caseId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  rejectLoan: TypedContractMethod<
    [loanId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  rejectRedeem: TypedContractMethod<
    [redeemId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  removeAuditor: TypedContractMethod<
    [auditor: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  repayLoan: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  requestLoan: TypedContractMethod<
    [principal: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  riskEngine: TypedContractMethod<[], [string], "view">;

  setBlacklist: TypedContractMethod<
    [user: AddressLike, isBlacklisted_: boolean],
    [void],
    "nonpayable"
  >;

  setDepositApyBps: TypedContractMethod<
    [bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFrequencyParams: TypedContractMethod<
    [windowSec: BigNumberish, maxCount: BigNumberish, lockSec: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  token: TypedContractMethod<[], [string], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unlockAccount: TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "AUDITOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TEN_K"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addAuditor"
  ): TypedContractMethod<[auditor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveEscrow"
  ): TypedContractMethod<[caseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveLoan"
  ): TypedContractMethod<
    [loanId: BigNumberish, ethAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveRedeem"
  ): TypedContractMethod<[redeemId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "blacklisted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "dailyStats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { day: bigint; spent: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositApyBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositFromExternal"
  ): TypedContractMethod<[susdAmount: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "ethPerSUSDE18"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "forceLockAccount"
  ): TypedContractMethod<
    [user: AddressLike, until: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "freqStats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { windowStart: bigint; count: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "frequencyWindow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [caseId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        from_: string;
        to_: string;
        amount_: bigint;
        status_: bigint;
        createdAt_: bigint;
        approvals_: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLoanCase"
  ): TypedContractMethod<
    [loanId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        borrower_: string;
        principal_: bigint;
        rateBps_: bigint;
        status_: bigint;
        createdAt_: bigint;
        approvals_: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRedeemCase"
  ): TypedContractMethod<
    [redeemId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        user_: string;
        assetSymbol_: string;
        susdAmount_: bigint;
        ethAmount_: bigint;
        status_: bigint;
        createdAt_: bigint;
        approvals_: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "identity"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lockDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockedUntil"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "logContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxTxPerWindow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextCaseId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextLoanId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextRedeemId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "redeemToAsset"
  ): TypedContractMethod<
    [assetSymbol: string, susdAmount: BigNumberish, ethAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectEscrow"
  ): TypedContractMethod<
    [caseId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectLoan"
  ): TypedContractMethod<
    [loanId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectRedeem"
  ): TypedContractMethod<
    [redeemId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeAuditor"
  ): TypedContractMethod<[auditor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repayLoan"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestLoan"
  ): TypedContractMethod<[principal: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "riskEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setBlacklist"
  ): TypedContractMethod<
    [user: AddressLike, isBlacklisted_: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDepositApyBps"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFrequencyParams"
  ): TypedContractMethod<
    [windowSec: BigNumberish, maxCount: BigNumberish, lockSec: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unlockAccount"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowApproved"
  ): TypedContractEvent<
    EscrowApprovedEvent.InputTuple,
    EscrowApprovedEvent.OutputTuple,
    EscrowApprovedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRejected"
  ): TypedContractEvent<
    EscrowRejectedEvent.InputTuple,
    EscrowRejectedEvent.OutputTuple,
    EscrowRejectedEvent.OutputObject
  >;
  getEvent(
    key: "ImmediateTransfer"
  ): TypedContractEvent<
    ImmediateTransferEvent.InputTuple,
    ImmediateTransferEvent.OutputTuple,
    ImmediateTransferEvent.OutputObject
  >;
  getEvent(
    key: "LoanApproved"
  ): TypedContractEvent<
    LoanApprovedEvent.InputTuple,
    LoanApprovedEvent.OutputTuple,
    LoanApprovedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRejected"
  ): TypedContractEvent<
    LoanRejectedEvent.InputTuple,
    LoanRejectedEvent.OutputTuple,
    LoanRejectedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "LoanRequested"
  ): TypedContractEvent<
    LoanRequestedEvent.InputTuple,
    LoanRequestedEvent.OutputTuple,
    LoanRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RedeemApproved"
  ): TypedContractEvent<
    RedeemApprovedEvent.InputTuple,
    RedeemApprovedEvent.OutputTuple,
    RedeemApprovedEvent.OutputObject
  >;
  getEvent(
    key: "RedeemRejected"
  ): TypedContractEvent<
    RedeemRejectedEvent.InputTuple,
    RedeemRejectedEvent.OutputTuple,
    RedeemRejectedEvent.OutputObject
  >;
  getEvent(
    key: "RedeemRequested"
  ): TypedContractEvent<
    RedeemRequestedEvent.InputTuple,
    RedeemRequestedEvent.OutputTuple,
    RedeemRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "EscrowApproved(uint256,address,address,uint256)": TypedContractEvent<
      EscrowApprovedEvent.InputTuple,
      EscrowApprovedEvent.OutputTuple,
      EscrowApprovedEvent.OutputObject
    >;
    EscrowApproved: TypedContractEvent<
      EscrowApprovedEvent.InputTuple,
      EscrowApprovedEvent.OutputTuple,
      EscrowApprovedEvent.OutputObject
    >;

    "EscrowCreated(uint256,address,address,uint256)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowRejected(uint256,address,address,uint256,string)": TypedContractEvent<
      EscrowRejectedEvent.InputTuple,
      EscrowRejectedEvent.OutputTuple,
      EscrowRejectedEvent.OutputObject
    >;
    EscrowRejected: TypedContractEvent<
      EscrowRejectedEvent.InputTuple,
      EscrowRejectedEvent.OutputTuple,
      EscrowRejectedEvent.OutputObject
    >;

    "ImmediateTransfer(address,address,uint256)": TypedContractEvent<
      ImmediateTransferEvent.InputTuple,
      ImmediateTransferEvent.OutputTuple,
      ImmediateTransferEvent.OutputObject
    >;
    ImmediateTransfer: TypedContractEvent<
      ImmediateTransferEvent.InputTuple,
      ImmediateTransferEvent.OutputTuple,
      ImmediateTransferEvent.OutputObject
    >;

    "LoanApproved(uint256,address,uint256)": TypedContractEvent<
      LoanApprovedEvent.InputTuple,
      LoanApprovedEvent.OutputTuple,
      LoanApprovedEvent.OutputObject
    >;
    LoanApproved: TypedContractEvent<
      LoanApprovedEvent.InputTuple,
      LoanApprovedEvent.OutputTuple,
      LoanApprovedEvent.OutputObject
    >;

    "LoanRejected(uint256,address,uint256,string)": TypedContractEvent<
      LoanRejectedEvent.InputTuple,
      LoanRejectedEvent.OutputTuple,
      LoanRejectedEvent.OutputObject
    >;
    LoanRejected: TypedContractEvent<
      LoanRejectedEvent.InputTuple,
      LoanRejectedEvent.OutputTuple,
      LoanRejectedEvent.OutputObject
    >;

    "LoanRepaid(address,uint256)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "LoanRequested(uint256,address,uint256,uint256)": TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;
    LoanRequested: TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;

    "RedeemApproved(uint256,address,uint256,uint256)": TypedContractEvent<
      RedeemApprovedEvent.InputTuple,
      RedeemApprovedEvent.OutputTuple,
      RedeemApprovedEvent.OutputObject
    >;
    RedeemApproved: TypedContractEvent<
      RedeemApprovedEvent.InputTuple,
      RedeemApprovedEvent.OutputTuple,
      RedeemApprovedEvent.OutputObject
    >;

    "RedeemRejected(uint256,address,uint256,string)": TypedContractEvent<
      RedeemRejectedEvent.InputTuple,
      RedeemRejectedEvent.OutputTuple,
      RedeemRejectedEvent.OutputObject
    >;
    RedeemRejected: TypedContractEvent<
      RedeemRejectedEvent.InputTuple,
      RedeemRejectedEvent.OutputTuple,
      RedeemRejectedEvent.OutputObject
    >;

    "RedeemRequested(uint256,address,string,uint256)": TypedContractEvent<
      RedeemRequestedEvent.InputTuple,
      RedeemRequestedEvent.OutputTuple,
      RedeemRequestedEvent.OutputObject
    >;
    RedeemRequested: TypedContractEvent<
      RedeemRequestedEvent.InputTuple,
      RedeemRequestedEvent.OutputTuple,
      RedeemRequestedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
