/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ComplianceLogInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "emitAMLAlert"
      | "emitAccountLocked"
      | "emitAccountUnlocked"
      | "emitAuditorAdded"
      | "emitAuditorRemoved"
      | "emitBlacklistUpdated"
      | "emitEDDRequested"
      | "emitGlobalParamUpdated"
      | "emitTransferApproved"
      | "emitTransferEscrowed"
      | "emitTransferRejected"
      | "emitTransferRequested"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AMLAlert"
      | "AccountLocked"
      | "AccountUnlocked"
      | "AuditorAdded"
      | "AuditorRemoved"
      | "BlacklistUpdated"
      | "EDDRequested"
      | "GlobalParamUpdated"
      | "TransferApproved"
      | "TransferEscrowed"
      | "TransferRejected"
      | "TransferRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "emitAMLAlert",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "emitAccountLocked",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "emitAccountUnlocked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emitAuditorAdded",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emitAuditorRemoved",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emitBlacklistUpdated",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "emitEDDRequested",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "emitGlobalParamUpdated",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emitTransferApproved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emitTransferEscrowed",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "emitTransferRejected",
    values: [BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "emitTransferRequested",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "emitAMLAlert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitAccountLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitAccountUnlocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitAuditorAdded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitAuditorRemoved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitBlacklistUpdated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitEDDRequested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitGlobalParamUpdated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitTransferApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitTransferEscrowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitTransferRejected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitTransferRequested",
    data: BytesLike
  ): Result;
}

export namespace AMLAlertEvent {
  export type InputTuple = [
    user: AddressLike,
    alertType: string,
    details: string
  ];
  export type OutputTuple = [user: string, alertType: string, details: string];
  export interface OutputObject {
    user: string;
    alertType: string;
    details: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccountLockedEvent {
  export type InputTuple = [
    user: AddressLike,
    until: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [user: string, until: bigint, reason: string];
  export interface OutputObject {
    user: string;
    until: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccountUnlockedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditorAddedEvent {
  export type InputTuple = [auditor: AddressLike];
  export type OutputTuple = [auditor: string];
  export interface OutputObject {
    auditor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditorRemovedEvent {
  export type InputTuple = [auditor: AddressLike];
  export type OutputTuple = [auditor: string];
  export interface OutputObject {
    auditor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BlacklistUpdatedEvent {
  export type InputTuple = [who: AddressLike, isBlacklisted: boolean];
  export type OutputTuple = [who: string, isBlacklisted: boolean];
  export interface OutputObject {
    who: string;
    isBlacklisted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EDDRequestedEvent {
  export type InputTuple = [
    user: AddressLike,
    caseId: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [user: string, caseId: bigint, reason: string];
  export interface OutputObject {
    user: string;
    caseId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalParamUpdatedEvent {
  export type InputTuple = [
    paramName: string,
    oldValue: BytesLike,
    newValue: BytesLike
  ];
  export type OutputTuple = [
    paramName: string,
    oldValue: string,
    newValue: string
  ];
  export interface OutputObject {
    paramName: string;
    oldValue: string;
    newValue: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferApprovedEvent {
  export type InputTuple = [caseId: BigNumberish, auditor: AddressLike];
  export type OutputTuple = [caseId: bigint, auditor: string];
  export interface OutputObject {
    caseId: bigint;
    auditor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEscrowedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    caseId: bigint,
    from: string,
    to: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    caseId: bigint;
    from: string;
    to: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRejectedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    auditor: AddressLike,
    reason: string
  ];
  export type OutputTuple = [caseId: bigint, auditor: string, reason: string];
  export interface OutputObject {
    caseId: bigint;
    auditor: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRequestedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    caseId: bigint,
    from: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    caseId: bigint;
    from: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComplianceLog extends BaseContract {
  connect(runner?: ContractRunner | null): ComplianceLog;
  waitForDeployment(): Promise<this>;

  interface: ComplianceLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  emitAMLAlert: TypedContractMethod<
    [user: AddressLike, alertType: string, details: string],
    [void],
    "nonpayable"
  >;

  emitAccountLocked: TypedContractMethod<
    [user: AddressLike, until: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  emitAccountUnlocked: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  emitAuditorAdded: TypedContractMethod<
    [auditor: AddressLike],
    [void],
    "nonpayable"
  >;

  emitAuditorRemoved: TypedContractMethod<
    [auditor: AddressLike],
    [void],
    "nonpayable"
  >;

  emitBlacklistUpdated: TypedContractMethod<
    [who: AddressLike, isBlacklisted: boolean],
    [void],
    "nonpayable"
  >;

  emitEDDRequested: TypedContractMethod<
    [user: AddressLike, caseId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  emitGlobalParamUpdated: TypedContractMethod<
    [paramName: string, oldValue: BytesLike, newValue: BytesLike],
    [void],
    "nonpayable"
  >;

  emitTransferApproved: TypedContractMethod<
    [caseId: BigNumberish, auditor: AddressLike],
    [void],
    "nonpayable"
  >;

  emitTransferEscrowed: TypedContractMethod<
    [
      caseId: BigNumberish,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      reason: string
    ],
    [void],
    "nonpayable"
  >;

  emitTransferRejected: TypedContractMethod<
    [caseId: BigNumberish, auditor: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  emitTransferRequested: TypedContractMethod<
    [
      caseId: BigNumberish,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "emitAMLAlert"
  ): TypedContractMethod<
    [user: AddressLike, alertType: string, details: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitAccountLocked"
  ): TypedContractMethod<
    [user: AddressLike, until: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitAccountUnlocked"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emitAuditorAdded"
  ): TypedContractMethod<[auditor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emitAuditorRemoved"
  ): TypedContractMethod<[auditor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emitBlacklistUpdated"
  ): TypedContractMethod<
    [who: AddressLike, isBlacklisted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitEDDRequested"
  ): TypedContractMethod<
    [user: AddressLike, caseId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitGlobalParamUpdated"
  ): TypedContractMethod<
    [paramName: string, oldValue: BytesLike, newValue: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitTransferApproved"
  ): TypedContractMethod<
    [caseId: BigNumberish, auditor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitTransferEscrowed"
  ): TypedContractMethod<
    [
      caseId: BigNumberish,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitTransferRejected"
  ): TypedContractMethod<
    [caseId: BigNumberish, auditor: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitTransferRequested"
  ): TypedContractMethod<
    [
      caseId: BigNumberish,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AMLAlert"
  ): TypedContractEvent<
    AMLAlertEvent.InputTuple,
    AMLAlertEvent.OutputTuple,
    AMLAlertEvent.OutputObject
  >;
  getEvent(
    key: "AccountLocked"
  ): TypedContractEvent<
    AccountLockedEvent.InputTuple,
    AccountLockedEvent.OutputTuple,
    AccountLockedEvent.OutputObject
  >;
  getEvent(
    key: "AccountUnlocked"
  ): TypedContractEvent<
    AccountUnlockedEvent.InputTuple,
    AccountUnlockedEvent.OutputTuple,
    AccountUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "AuditorAdded"
  ): TypedContractEvent<
    AuditorAddedEvent.InputTuple,
    AuditorAddedEvent.OutputTuple,
    AuditorAddedEvent.OutputObject
  >;
  getEvent(
    key: "AuditorRemoved"
  ): TypedContractEvent<
    AuditorRemovedEvent.InputTuple,
    AuditorRemovedEvent.OutputTuple,
    AuditorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "BlacklistUpdated"
  ): TypedContractEvent<
    BlacklistUpdatedEvent.InputTuple,
    BlacklistUpdatedEvent.OutputTuple,
    BlacklistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EDDRequested"
  ): TypedContractEvent<
    EDDRequestedEvent.InputTuple,
    EDDRequestedEvent.OutputTuple,
    EDDRequestedEvent.OutputObject
  >;
  getEvent(
    key: "GlobalParamUpdated"
  ): TypedContractEvent<
    GlobalParamUpdatedEvent.InputTuple,
    GlobalParamUpdatedEvent.OutputTuple,
    GlobalParamUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TransferApproved"
  ): TypedContractEvent<
    TransferApprovedEvent.InputTuple,
    TransferApprovedEvent.OutputTuple,
    TransferApprovedEvent.OutputObject
  >;
  getEvent(
    key: "TransferEscrowed"
  ): TypedContractEvent<
    TransferEscrowedEvent.InputTuple,
    TransferEscrowedEvent.OutputTuple,
    TransferEscrowedEvent.OutputObject
  >;
  getEvent(
    key: "TransferRejected"
  ): TypedContractEvent<
    TransferRejectedEvent.InputTuple,
    TransferRejectedEvent.OutputTuple,
    TransferRejectedEvent.OutputObject
  >;
  getEvent(
    key: "TransferRequested"
  ): TypedContractEvent<
    TransferRequestedEvent.InputTuple,
    TransferRequestedEvent.OutputTuple,
    TransferRequestedEvent.OutputObject
  >;

  filters: {
    "AMLAlert(address,string,string)": TypedContractEvent<
      AMLAlertEvent.InputTuple,
      AMLAlertEvent.OutputTuple,
      AMLAlertEvent.OutputObject
    >;
    AMLAlert: TypedContractEvent<
      AMLAlertEvent.InputTuple,
      AMLAlertEvent.OutputTuple,
      AMLAlertEvent.OutputObject
    >;

    "AccountLocked(address,uint256,string)": TypedContractEvent<
      AccountLockedEvent.InputTuple,
      AccountLockedEvent.OutputTuple,
      AccountLockedEvent.OutputObject
    >;
    AccountLocked: TypedContractEvent<
      AccountLockedEvent.InputTuple,
      AccountLockedEvent.OutputTuple,
      AccountLockedEvent.OutputObject
    >;

    "AccountUnlocked(address)": TypedContractEvent<
      AccountUnlockedEvent.InputTuple,
      AccountUnlockedEvent.OutputTuple,
      AccountUnlockedEvent.OutputObject
    >;
    AccountUnlocked: TypedContractEvent<
      AccountUnlockedEvent.InputTuple,
      AccountUnlockedEvent.OutputTuple,
      AccountUnlockedEvent.OutputObject
    >;

    "AuditorAdded(address)": TypedContractEvent<
      AuditorAddedEvent.InputTuple,
      AuditorAddedEvent.OutputTuple,
      AuditorAddedEvent.OutputObject
    >;
    AuditorAdded: TypedContractEvent<
      AuditorAddedEvent.InputTuple,
      AuditorAddedEvent.OutputTuple,
      AuditorAddedEvent.OutputObject
    >;

    "AuditorRemoved(address)": TypedContractEvent<
      AuditorRemovedEvent.InputTuple,
      AuditorRemovedEvent.OutputTuple,
      AuditorRemovedEvent.OutputObject
    >;
    AuditorRemoved: TypedContractEvent<
      AuditorRemovedEvent.InputTuple,
      AuditorRemovedEvent.OutputTuple,
      AuditorRemovedEvent.OutputObject
    >;

    "BlacklistUpdated(address,bool)": TypedContractEvent<
      BlacklistUpdatedEvent.InputTuple,
      BlacklistUpdatedEvent.OutputTuple,
      BlacklistUpdatedEvent.OutputObject
    >;
    BlacklistUpdated: TypedContractEvent<
      BlacklistUpdatedEvent.InputTuple,
      BlacklistUpdatedEvent.OutputTuple,
      BlacklistUpdatedEvent.OutputObject
    >;

    "EDDRequested(address,uint256,string)": TypedContractEvent<
      EDDRequestedEvent.InputTuple,
      EDDRequestedEvent.OutputTuple,
      EDDRequestedEvent.OutputObject
    >;
    EDDRequested: TypedContractEvent<
      EDDRequestedEvent.InputTuple,
      EDDRequestedEvent.OutputTuple,
      EDDRequestedEvent.OutputObject
    >;

    "GlobalParamUpdated(string,bytes32,bytes32)": TypedContractEvent<
      GlobalParamUpdatedEvent.InputTuple,
      GlobalParamUpdatedEvent.OutputTuple,
      GlobalParamUpdatedEvent.OutputObject
    >;
    GlobalParamUpdated: TypedContractEvent<
      GlobalParamUpdatedEvent.InputTuple,
      GlobalParamUpdatedEvent.OutputTuple,
      GlobalParamUpdatedEvent.OutputObject
    >;

    "TransferApproved(uint256,address)": TypedContractEvent<
      TransferApprovedEvent.InputTuple,
      TransferApprovedEvent.OutputTuple,
      TransferApprovedEvent.OutputObject
    >;
    TransferApproved: TypedContractEvent<
      TransferApprovedEvent.InputTuple,
      TransferApprovedEvent.OutputTuple,
      TransferApprovedEvent.OutputObject
    >;

    "TransferEscrowed(uint256,address,address,uint256,string)": TypedContractEvent<
      TransferEscrowedEvent.InputTuple,
      TransferEscrowedEvent.OutputTuple,
      TransferEscrowedEvent.OutputObject
    >;
    TransferEscrowed: TypedContractEvent<
      TransferEscrowedEvent.InputTuple,
      TransferEscrowedEvent.OutputTuple,
      TransferEscrowedEvent.OutputObject
    >;

    "TransferRejected(uint256,address,string)": TypedContractEvent<
      TransferRejectedEvent.InputTuple,
      TransferRejectedEvent.OutputTuple,
      TransferRejectedEvent.OutputObject
    >;
    TransferRejected: TypedContractEvent<
      TransferRejectedEvent.InputTuple,
      TransferRejectedEvent.OutputTuple,
      TransferRejectedEvent.OutputObject
    >;

    "TransferRequested(uint256,address,address,uint256)": TypedContractEvent<
      TransferRequestedEvent.InputTuple,
      TransferRequestedEvent.OutputTuple,
      TransferRequestedEvent.OutputObject
    >;
    TransferRequested: TypedContractEvent<
      TransferRequestedEvent.InputTuple,
      TransferRequestedEvent.OutputTuple,
      TransferRequestedEvent.OutputObject
    >;
  };
}
