/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RiskEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "RISK_OFFICER_ROLE"
      | "baseInterestBps"
      | "calculateUtilizationRateBps"
      | "getDailyLimit"
      | "getDepositRateBps"
      | "getInterestRateBps"
      | "getRiskScore"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initRisk"
      | "optimalUtilization"
      | "renounceRole"
      | "reserveFactorBps"
      | "revokeRole"
      | "riskProfiles"
      | "riskSlopeBps"
      | "setBaseInterestBps"
      | "setRiskSlopeBps"
      | "slope1Bps"
      | "slope2Bps"
      | "supportsInterface"
      | "updateRisk"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BaseInterestUpdated"
      | "RiskInitialized"
      | "RiskSlopeUpdated"
      | "RiskUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RISK_OFFICER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseInterestBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateUtilizationRateBps",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDailyLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositRateBps",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInterestRateBps",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRiskScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initRisk",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "optimalUtilization",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveFactorBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "riskProfiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "riskSlopeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseInterestBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRiskSlopeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "slope1Bps", values?: undefined): string;
  encodeFunctionData(functionFragment: "slope2Bps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRisk",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RISK_OFFICER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseInterestBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateUtilizationRateBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositRateBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInterestRateBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initRisk", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "optimalUtilization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveFactorBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "riskProfiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "riskSlopeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseInterestBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRiskSlopeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "slope1Bps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "slope2Bps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateRisk", data: BytesLike): Result;
}

export namespace BaseInterestUpdatedEvent {
  export type InputTuple = [newBaseBps: BigNumberish];
  export type OutputTuple = [newBaseBps: bigint];
  export interface OutputObject {
    newBaseBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskInitializedEvent {
  export type InputTuple = [
    user: AddressLike,
    score: BigNumberish,
    dailyLimit: BigNumberish
  ];
  export type OutputTuple = [user: string, score: bigint, dailyLimit: bigint];
  export interface OutputObject {
    user: string;
    score: bigint;
    dailyLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskSlopeUpdatedEvent {
  export type InputTuple = [newSlopeBps: BigNumberish];
  export type OutputTuple = [newSlopeBps: bigint];
  export interface OutputObject {
    newSlopeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    score: BigNumberish,
    dailyLimit: BigNumberish
  ];
  export type OutputTuple = [user: string, score: bigint, dailyLimit: bigint];
  export interface OutputObject {
    user: string;
    score: bigint;
    dailyLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RiskEngine extends BaseContract {
  connect(runner?: ContractRunner | null): RiskEngine;
  waitForDeployment(): Promise<this>;

  interface: RiskEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  RISK_OFFICER_ROLE: TypedContractMethod<[], [string], "view">;

  baseInterestBps: TypedContractMethod<[], [bigint], "view">;

  calculateUtilizationRateBps: TypedContractMethod<
    [totalBorrowed: BigNumberish, totalLiquidity: BigNumberish],
    [bigint],
    "view"
  >;

  getDailyLimit: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getDepositRateBps: TypedContractMethod<
    [totalBorrowed: BigNumberish, totalDeposits: BigNumberish],
    [bigint],
    "view"
  >;

  getInterestRateBps: TypedContractMethod<
    [
      user: AddressLike,
      totalBorrowed: BigNumberish,
      totalLiquidity: BigNumberish
    ],
    [bigint],
    "view"
  >;

  getRiskScore: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initRisk: TypedContractMethod<
    [user: AddressLike, score: BigNumberish, dailyLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  optimalUtilization: TypedContractMethod<[], [bigint], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  reserveFactorBps: TypedContractMethod<[], [bigint], "view">;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  riskProfiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        riskScore: bigint;
        dailyTransferLimit: bigint;
        lastUpdatedAt: bigint;
      }
    ],
    "view"
  >;

  riskSlopeBps: TypedContractMethod<[], [bigint], "view">;

  setBaseInterestBps: TypedContractMethod<
    [newBaseBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRiskSlopeBps: TypedContractMethod<
    [newSlopeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  slope1Bps: TypedContractMethod<[], [bigint], "view">;

  slope2Bps: TypedContractMethod<[], [bigint], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateRisk: TypedContractMethod<
    [user: AddressLike, newScore: BigNumberish, newDailyLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RISK_OFFICER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "baseInterestBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateUtilizationRateBps"
  ): TypedContractMethod<
    [totalBorrowed: BigNumberish, totalLiquidity: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDailyLimit"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDepositRateBps"
  ): TypedContractMethod<
    [totalBorrowed: BigNumberish, totalDeposits: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInterestRateBps"
  ): TypedContractMethod<
    [
      user: AddressLike,
      totalBorrowed: BigNumberish,
      totalLiquidity: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRiskScore"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initRisk"
  ): TypedContractMethod<
    [user: AddressLike, score: BigNumberish, dailyLimit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "optimalUtilization"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reserveFactorBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "riskProfiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        riskScore: bigint;
        dailyTransferLimit: bigint;
        lastUpdatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "riskSlopeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setBaseInterestBps"
  ): TypedContractMethod<[newBaseBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRiskSlopeBps"
  ): TypedContractMethod<[newSlopeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slope1Bps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "slope2Bps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateRisk"
  ): TypedContractMethod<
    [user: AddressLike, newScore: BigNumberish, newDailyLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BaseInterestUpdated"
  ): TypedContractEvent<
    BaseInterestUpdatedEvent.InputTuple,
    BaseInterestUpdatedEvent.OutputTuple,
    BaseInterestUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RiskInitialized"
  ): TypedContractEvent<
    RiskInitializedEvent.InputTuple,
    RiskInitializedEvent.OutputTuple,
    RiskInitializedEvent.OutputObject
  >;
  getEvent(
    key: "RiskSlopeUpdated"
  ): TypedContractEvent<
    RiskSlopeUpdatedEvent.InputTuple,
    RiskSlopeUpdatedEvent.OutputTuple,
    RiskSlopeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RiskUpdated"
  ): TypedContractEvent<
    RiskUpdatedEvent.InputTuple,
    RiskUpdatedEvent.OutputTuple,
    RiskUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "BaseInterestUpdated(uint256)": TypedContractEvent<
      BaseInterestUpdatedEvent.InputTuple,
      BaseInterestUpdatedEvent.OutputTuple,
      BaseInterestUpdatedEvent.OutputObject
    >;
    BaseInterestUpdated: TypedContractEvent<
      BaseInterestUpdatedEvent.InputTuple,
      BaseInterestUpdatedEvent.OutputTuple,
      BaseInterestUpdatedEvent.OutputObject
    >;

    "RiskInitialized(address,uint8,uint256)": TypedContractEvent<
      RiskInitializedEvent.InputTuple,
      RiskInitializedEvent.OutputTuple,
      RiskInitializedEvent.OutputObject
    >;
    RiskInitialized: TypedContractEvent<
      RiskInitializedEvent.InputTuple,
      RiskInitializedEvent.OutputTuple,
      RiskInitializedEvent.OutputObject
    >;

    "RiskSlopeUpdated(uint256)": TypedContractEvent<
      RiskSlopeUpdatedEvent.InputTuple,
      RiskSlopeUpdatedEvent.OutputTuple,
      RiskSlopeUpdatedEvent.OutputObject
    >;
    RiskSlopeUpdated: TypedContractEvent<
      RiskSlopeUpdatedEvent.InputTuple,
      RiskSlopeUpdatedEvent.OutputTuple,
      RiskSlopeUpdatedEvent.OutputObject
    >;

    "RiskUpdated(address,uint8,uint256)": TypedContractEvent<
      RiskUpdatedEvent.InputTuple,
      RiskUpdatedEvent.OutputTuple,
      RiskUpdatedEvent.OutputObject
    >;
    RiskUpdated: TypedContractEvent<
      RiskUpdatedEvent.InputTuple,
      RiskUpdatedEvent.OutputTuple,
      RiskUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
